quizapplication/quizapplication/quizapplication/urls.py
from django.contrib import admin
from django.urls import path,include
from quiz import views
from rest_framework.routers import DefaultRouter
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView

router=DefaultRouter()
router.register("api/v1/categories",views.CategoriesView,basename="category")
router.register("api/v1/questions",views.QuestionView,basename="question")

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/v1/token/',ObtainAuthToken.as_view())
    path("api/v1/token/",TokenObtainPairView.as_view()),
    path("api/v1/token/refresh/",TokenRefreshView.as_view()),
    path("web/",include("quizweb.urls"))
    

]+router.urls

quizapplication/quizapplication/quizweb/urls.py
from django.urls import path
from quizweb import views



urlpatterns=[
    path("login",views.SignInView.as_view(),name="signup"),
    path("register",views.SignUpView.as_view(),name="signin"),
    path("home",views.HomeView.as_view(),name="home"),
    path("home/quiz",views.QuizHome.as_view(),name="quiz-home"),
    path("questions/all/<str:cat>/<str:mode>/",views.QuestionList.as_view(),name="question-list"),
    path("questions/record",views.QuizrecordView.as_view(),name="quiz-record"),
    path("",views.IndexView.as_view(),name="index"),
    path("signout",views.signout_view,name="signout"),
]

quizapplication/quizapplication/quiz/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)
    is_active=models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.name

class Questions(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    options=(
        ('easy','easy'),
        ('medium','medium'),
        ('hard','hard')
    )
    mode=models.CharField(max_length=200,choices=options,default='easy')
    mark=models.PositiveIntegerField(default=2)
    question=models.CharField(max_length=200)
    
    @property
    def options(self):
        return Answers.objects.filter(question=self)
        
    @property
    def answer(self):
        return Answers.objects.get(question=self,is_correct=True)


    def __str__(self) -> str:
        return self.question



class Answers(models.Model):
    question=models.ForeignKey(Questions,on_delete=models.CASCADE)
    options=models.CharField(max_length=200)
    is_correct=models.BooleanField(default=False)


    def __str__(self) -> str:
        return self.options



class QuizRecord(models.Model):
    marks_obtained=models.PositiveIntegerField()
    right_answer_count=models.PositiveIntegerField()
    wrong_answer_count=models.PositiveIntegerField()
    user=models.ForeignKey(User, on_delete=models.DO_NOTHING)
    result=models.CharField(max_length=200,null=True)
    date=models.DateTimeField(auto_now_add=True)

quizapplication/quizapplication/quizweb/models.py
from django.db import models

# Create your models here.

quizapplication/quizapplication/quizweb/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm




class RegisterationForm(UserCreationForm):
    class Meta:
        model=User
        fields=["email","username","password1","password2"]

    
class LoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()
    

quizapplication/quizapplication/quizweb/views.py
from django.shortcuts import render,redirect
from quiz.models import Category,Questions,Answers,QuizRecord
from django.contrib.auth.models import User
from quizweb.forms import RegisterationForm,LoginForm
from django.views.generic import CreateView,View,FormView,TemplateView,ListView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
import random
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache

# Create your views here.
def signin_required(fn):
    def wrapper(request,*args,**kwargs):
        if  not request.user.is_authenticated:
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)
    return wrapper

decs=[signin_required,never_cache]

@signin_required
@never_cache
def signout_view(request,*args,**kwargs):
    logout(request)
    return redirect("signin")



class SignUpView(CreateView):
    form_class=RegisterationForm
    model=User
    template_name="register.html"
    success_url=reverse_lazy("signup")

    # def form_valid(self,form):
    #     messages.success(self.request,"account has been created")
    #     return super().form_valid(form)
    # def form_invalid(self, form):
    #     messages.error(self.request,"failed to create account")
    #     return super().form_valid(form)


class SignInView(FormView):
    form_class=LoginForm
    template_name='login.html'
    # success_url=reverse_lazy("#")
    def post(self, request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                return redirect("home")
            else:
                return render(request,"login.html",{"form":form})

@method_decorator(decs,name="dispatch")
class HomeView(TemplateView):
    template_name="home.html"


@method_decorator(decs,name="dispatch")
class QuizHome(View):
    def get(self,request,*args,**kwargs):
        qs=Category.objects.all()
        return render(request,"quiz-home.html",{"cats":qs})
    def post(self,request,*args,**kwargs):
        cat=request.POST.get("category")
        mode=request.POST.get("mode")
        print(cat,mode)
        return redirect("question-list",mode=mode,cat=cat)

@method_decorator(decs,name="dispatch")
class QuestionList(View):

    def get(self,request,*args,**kwargs):
        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        qs=list(Questions.objects.filter(category__name=category,mode=mode))
        

        random.shuffle(qs)
        return render(request,"question-list.html",{"questions":qs})

    def post(self,request,*args,**kwargs):
        category=kwargs.get("cat")
        mode=kwargs.get("mode")
        data=request.POST.dict()
        data.pop("csrfmiddlewaretoken")
        questions_attended=len(data)
        total_marks=0
        wrong_ans_count=0
        result=""
        qob=Questions.objects.filter(category__name=category,mode=mode)
        grand_total=0
        for q in qob:
            grand_total+=q.mark
        pass_mark=grand_total//2

        for q,ans in data.items():
            question=Questions.objects.get(question=q)
            right_ans_object=question.answer
            if (right_ans_object.options==ans):
                total_marks=total_marks+question.mark
            else:
                wrong_ans_count +=1
        right_ans_count=questions_attended-wrong_ans_count

        if total_marks>=pass_mark:
            print(request.user," passed the quiz")
            result="pass"
        else:
            print(request.user," failed the quiz")
            result="failed"
        print(f"hello user{request.user} total no of questions attempted={questions_attended} your total mark={total_marks} worng answers count={wrong_ans_count} ")

        data=QuizRecord.objects.create(marks_obtained=total_marks,right_answer_count=right_ans_count,wrong_answer_count=wrong_ans_count,user=request.user,result=result)
        return render(request,"quiz-mark.html",{"questions_attended":questions_attended,"total_marks":total_marks ,"result":result,"right_answer_count":right_ans_count,"wrong_answer_count":wrong_ans_count})
        
@method_decorator(decs,name="dispatch")
class QuizrecordView(ListView):
    model=QuizRecord
    template_name='quiz-record.html'
    context_object_name='records'

    def get_queryset(self):
        return QuizRecord.objects.filter(user=self.request.user)
        
class IndexView(TemplateView):
    template_name='index.html'

quizapplication/quizapplication/quizweb/templates/home.html
<!DOCTYPE html>
{%load static%}


<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top"></a>
                -- <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'signout' %}">
                          Logout
                        </a>
                      </li>
                    </ul> 
                  </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1 class="text-white font-weight-bold">Welcome To QuizLand.in</h1>
                        <hr class="divider" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5 ">The Best Mind Hunting Questions You Will Ever Find</p>
                        <a class="btn btn-primary btn-xl" href="{%url 'quiz-home'%}">Start Quiz</a>
                        <a class="btn btn-primary btn-xl" href="{%url 'quiz-record'%}">Records</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">We've got what you need!</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
                        <a class="btn btn-light btn-xl" href="#services">Get Started!</a>
                    </div>
                </div>
            </div>
        </section>
         -->
        <!-- Portfolio-->
        
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2023 - Mindhunter.in</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

quizapplication/quizapplication/quizweb/templates/index.html
<!DOCTYPE html>
{%load static%}


<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Creative - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#page-top"></a>
                <!-- <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div> -->
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-8 align-self-end">
                        <h1    class="text-black font-weight-bold">Mindhunter.com</h1>
                        <hr class=" color-black  divider  " />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 mb-5 "></p>
                        <a class="text-black    btn btn-primary btn-xl" href="{%url 'signup'%}">Login</a>
                        <a class="text-black    btn btn-primary btn-xl" href="{%url 'signin'%}">SignUp</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">We've got what you need!</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
                        <a class="btn btn-light btn-xl" href="#services">Get Started!</a>
                    </div>
                </div>
            </div>
        </section>
         -->
        <!-- Portfolio-->
        
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2023 - Mindhunter.in</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

quizapplication/quizapplication/quizweb/templates/quiz-home.html
<!DOCTYPE html>
{%load static%}

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Creative - Start Bootstrap Theme</title>
    <!-- Favicon-->
    <link
      rel="icon"
      type="image/x-icon"
      href="{%static 'assets/favicon.ico'%}"
    />
    <!-- Bootstrap Icons-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <!-- SimpleLightbox plugin CSS-->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
  </head>
  <body id="page-top">
    <!-- Navigation-->
    <nav
      class="navbar navbar-expand-lg navbar-light fixed-top py-3"
      id="mainNav"
    >
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#page-top"></a>
        <!-- <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div> -->
      </div>
    </nav>
    <!-- Masthead-->
    <header class="masthead">
      <div class="container px-4 px-lg-5 h-100">
        <div
          class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center"
        >
          <div class="col-lg-8 align-self-end">
            <h1 class="text-white font-weight-bold"></h1>
            <!-- <hr class="divider" /> -->
          </div>
          <div class="col-lg-8 align-self-baseline">
            <p class="text-white-75 mb-5"></p>
            <div class="container">
                <div class="row mt-5">
                    <div class="col-3"></div>
                    <div class="col-6">
                        <div class="container border rounded p-2 mt-4">
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <div class="col-6">
                                        <label for="id_category" class="form-label">Select a category:</label>
                                        <select name="category" id="id_category" class="form-select">
                                            {% for cat in cats %}
                                            <option value="{{ cat.name }}">{{ cat.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-6">
                                        <label for="id_mode" class="form-label">Select a difficulty:</label>
                                        <select name="mode" id="id_mode" class="form-select">
                                            <option value="easy">Easy</option>
                                            <option value="medium">Medium</option>
                                            <option value="hard">Hard</option>
                                        </select>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Let's start</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
            <!-- <a class="btn btn-primary btn-xl" href="{%url 'quiz-home'%}">Start Quiz</a> -->
            <!-- <a class="btn btn-primary btn-xl" href="{%url 'signin'%}">SignUp</a> -->
          </div>
        </div>
      </div>
    </header>
    <!-- About
        <section class="page-section bg-primary" id="about">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">We've got what you need!</h2>
                        <hr class="divider divider-light" />
                        <p class="text-white-75 mb-4">Start Bootstrap has everything you need to get your new website up and running in no time! Choose one of our open source, free to download, and easy to use themes! No strings attached!</p>
                        <a class="btn btn-light btn-xl" href="#services">Get Started!</a>
                    </div>
                </div>
            </div>
        </section>
         -->
    <!-- Portfolio-->

    <!-- Footer-->
    <footer class="bg-light py-5">
      <div class="container px-4 px-lg-5">
        <div class="small text-center text-muted">
          Copyright &copy; 2023 - Mindhunter.in
        </div>
      </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- SimpleLightbox plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
    <!-- Core theme JS-->
    <script src="{%static 'js/scripts.js'%}"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
</html>

quizapplication/quizapplication/quizweb/templates/register.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <title>Login 04</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <link rel="stylesheet" href="{%static 'web/css/style.css'%}" />
  </head>
  <body>
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5">
            <h2 class="heading-section"></h2>
          </div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="wrap d-md-flex">
              <div
                class="img"
                style="background-image: url({%static 'OIP.jpg'%})"
              ></div>
              <div class="login-wrap p-4 p-md-5">
                <div class="d-flex">
                  <div class="w-100">
                    <h3 class="mb-4">Sign In</h3>
                  </div>
                  <div class="w-100">
                    <p class="social-media d-flex justify-content-end">
                      <a
                        href="#"
                        class="social-icon d-flex align-items-center justify-content-center"
                        ><span class="fa fa-facebook"></span
                      ></a>
                      <a
                        href="#"
                        class="social-icon d-flex align-items-center justify-content-center"
                        ><span class="fa fa-twitter"></span
                      ></a>
                    </p>
                  </div>
                </div>
                <form action="#" class="signin-form" method="post">
					      {%csrf_token%}
                  <div class="form-group mb-3">
                    <label class="label" for="name">username</label>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Username"
					            name="username"
                      required
                    />
                  </div>
                  <div class="form-group mb-3">
                    <label class="label" for="name">email</label>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="email"
					            name="email"
                      required
                    />
                  </div>
                  <div class="form-group mb-3">
                    <label class="label" for="password">Password</label>
                    <input
                      type="password1"
                      class="form-control"
                      placeholder="Password1"
                      required
					            name="password1"
                    />
                  </div>
                  <div class="form-group mb-3">
                    <label class="label" for="password">Confirm password</label>
                    <input
                      type="password2"
                      class="form-control"
                      placeholder="Password2"
                      required
					            name="password2"
                    />
                  </div>
                  <div class="form-group">
                    <button
                      type="submit"
                      class="form-control btn btn-primary rounded submit px-3"
                    >
                      Sign Up                   </button>
                  </div>
                  <div class="form-group d-md-flex">
                    <div class="w-50 text-left">
                      <label class="checkbox-wrap checkbox-primary mb-0"
                        >Remember Me
                        <input type="checkbox" checked />
                        <span class="checkmark"></span>
                      </label>
                    </div>
                   
                  </div>
                </form>
                <p class="text-center">
                 Already a Member? <a href="{% url 'signup'%}">Sign In</a>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <script src="{%static 'web/js/jquery.min.js'%}"></script>
    <script src="{%static 'web/js/popper.js'%}"></script>
    <script src="{%static 'web/js/bootstrap.min.js'%}"></script>
    <script src="{%static 'web/js/main.js'%}"></script>
  </body>
</html>